[#645] Correct delta-lake persist failure
Delta-lake persisting fails with NoClassDefFoundError. Resolved by
adding the missing jar to the aissemble spark image